// frontend/src/components/Navbar.tsx
import { useState } from 'react';
import { NavLink, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import './Navbar.scss';

export function Navbar() {
  const [menuOpen, setMenuOpen] = useState(false);
  const { admin, logout } = useAuth();
  const navigate = useNavigate();

  function handleLogout() {
    setMenuOpen(false);
    logout();
    navigate('/login');
  }

  return (
    <nav className="navbar">
      <div className="navbar-brand">
        <span className="brand-icon">&#9685;</span>
        <NavLink className="brand-name" to="/dashboard">
          MyTourDataViewer
        </NavLink>
      </div>

      <button
        className={`nav-toggle${menuOpen ? ' open' : ''}`}
        onClick={() => setMenuOpen(v => !v)}
        aria-label="Toggle navigation"
      >
        <span />
        <span />
        <span />
      </button>

      <div className={`nav-links${menuOpen ? ' open' : ''}`} onClick={() => setMenuOpen(false)}>
        <NavLink to="/dashboard" end={false}>
          Dashboard
        </NavLink>
        {admin && (
          <>
            <NavLink to="/admin/users">Users</NavLink>
            <NavLink to="/admin/api-settings">API Settings</NavLink>
          </>
        )}
        <button type="button" className="btn-logout" onClick={handleLogout}>
          Logout
        </button>
      </div>
    </nav>
  );
}

// frontend/src/app/shared/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';

@Component({
  standalone: false,
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss'
})
export class NavbarComponent {
  menuOpen = false;

  constructor(
    private readonly authService: AuthService,
    private readonly router: Router
  ) {}

  logout(): void {
    this.menuOpen = false;
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}

<nav class="navbar">
  <div class="navbar-brand">
    <span class="brand-icon">&#9685;</span>
    <a class="brand-name" routerLink="/dashboard">MyTourDataViewer</a>
  </div>

  <button class="nav-toggle" (click)="menuOpen = !menuOpen" [class.open]="menuOpen" aria-label="Toggle navigation">
    <span></span><span></span><span></span>
  </button>

  <div class="nav-links" [class.open]="menuOpen" (click)="menuOpen = false">
    <a routerLink="/dashboard" routerLinkActive="active">Dashboard</a>
    <!-- TODO: show Admin links only for Administrator role -->
    <a routerLink="/admin/users" routerLinkActive="active">Users</a>
    <a routerLink="/admin/api-settings" routerLinkActive="active">API Settings</a>
    <button type="button" class="btn-logout" (click)="logout()">Logout</button>
  </div>
</nav>
